VRP_VARIANTS = [
    "CVRP", "VRPB", "VRPBL", "VRPBLTW", "VRPBTW", "VRPL", "VRPLTW",
    "VRPMB", "VRPMBL", "VRPMBLTW", "VRPMBTW", "VRPTW",
    "OVRP", "OVRPB", "OVRPBL", "OVRPBLTW", "OVRPBTW", "OVRPL",
    "OVRPLTW", "OVRPMB", "OVRPMBL", "OVRPMBLTW", "OVRPMBTW", "OVRPTW"
]

# SP_VARIANTS = [
#     "JSSP", "FJSSP", "FSSP", "HFSSP", "OSSP", "ASP",
# ]

SP_VARIANTS = [
    'JSSP'
]