[instance]
online_arrivals = false         # false for static instance (from data) or true for online job arrivals
problem_instance = "/fjsp_sdst/fattahi/Fattahi_setup_20.fjs"  # static instance (no online arrivals)
dispatching_rule = "MOR"        # FIFO: First In First Out, MOR: Most Operation Remaining, LOR: Least Operations Remaining,
                                # MWR: Most Work Remaining, LWR: Least Work Remaining
machine_assignment_rule = "EET" # SPT: Shortest Processing Time, EET: Earliest End Time

[online_arrival_details]        # Only needed for_online arrivals = true
number_total_machines = 5       # number of machines
inter_arrival_time = 15         # inter_arrival_time between jobs
simulation_time = 500           # simulation duration time
min_nr_operations_per_job = 2   # min number of operations per online arrived job
max_nr_operations_per_job = 7   # max number of operations per online arrived job
min_duration_per_operation = 2  # min duration of online arrived operation
max_duration_per_operation = 40 # max duration of online arrived operation

[output]
logbook = true                  # display logbook during search
show_precedences = true         # draw precedence relations graph of the problem instance
show_gantt = true               # draw ganttchart of found solution
save_gantt = true               # save ganttchart to file
save_results = true             # save results to file
exp_name = ""                   # name of the experiment, used for saving results.
                                # If empty (""), the name of the problem instance is used
folder = ""                     # folder to save results, used for saving results.
                                # If empty (""), the results are saved to the current working directory.
